#!/bin/bash
set -e  # Stop the script if any command fails

# Update the system
sudo yum update -y

# Install Docker
sudo amazon-linux-extras enable docker
sudo yum install -y docker

# Add the ec2-user to the Docker group to allow running containers without sudo
sudo usermod -aG docker ec2-user

# Start Docker and enable it to start automatically on boot
sudo systemctl start docker
sudo systemctl enable docker
sudo systemctl restart docker  # Ensure the service starts properly

# Verify installation
docker --version
