#!/bin/bash
set -e  # עצור את הסקריפט אם יש שגיאה כלשהי

# עדכון המערכת
sudo yum update -y

# התקנת Docker
sudo amazon-linux-extras enable docker
sudo yum install -y docker

# הפעלת Docker
sudo systemctl start docker
sudo systemctl enable docker
